<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tours"
 *
 * Auto generated by Extension Builder 2015-11-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Autocars Tours',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Sergey Borulko, Vadym Girkalo',
    'author_email' => 'sergey.borulko@nazomi.com, gvv100@gmail.com',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
